=== zc0nf/drftpd2/files.dtd
<!-- ENTRY TYPES -->
<!ELEMENT directory (user, group, lastModified, contents, slaves)>
<!ATTLIST directory
	name CDATA #REQUIRED>

<!ELEMENT file (user, group, checksum, size, lastModified, slaves)>
<!ATTLIST file name CDATA #REQUIRED>

<!ELEMENT contents (file?, directory?)*>

<!-- FILE ATTRIBUTES -->
<!ELEMENT user (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT checksum (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT lastModified (#PCDATA)>

<!-- SLAVES -->
<!ELEMENT slaves (slave*)?>

<!ELEMENT slave EMPTY>
<!ATTLIST slave
	name CDATA #REQUIRED>

=== zc0nf/drftpd2/trunk/files.xml
<?xml version="1.0"?>
<!DOCTYPE directory SYSTEM "files.dtd">
<directory name="/">
	<user>drftpd</user>
	<group>drftpd</group>
	<lastModified>1029801971</lastModified>
	<contents>
		<directory name="DIVX">
			<user>drftpd</user>
			<group>drftpd</group>
			<lastModified>1029801971</lastModified>
			<contents/>
			<slaves>
				<slave name="mog"/>
			</slaves>
		</directory>
		<file name=".message">
			<user>drftpd</user>
			<group>drftpd</group>
			<checksum/>
			<size>0</size>
			<lastModified>1029801971</lastModified>
			<slaves>
				<slave name="mog"/>
			</slaves>
		</file>
	</contents>
	<slaves>
		<slave name="mog"/>
	</slaves>
</directory>
